GitHub Actionsの設定
GitHub Actionsを使うのは初めてなので最適解かどうかはわかりませんが，ひとまず動くリポジトリを下記に残しておきます。

GitHub - YoshiRi/MarkdownToAsciidocToHTML_CI: GitHub Action Test
https://github.com


ざっくりとした動作原理
きちんと語れるほど詳しくないですが.github/workflows/hoge.ymlというファイルを設定することでActionsを設定出来ます。

今回は変更がPushされたときに起動するアクションを設定しました。

流れとしては，下記のようになっています。

Github Workspaceにリポジトリのファイルをチェックアウト
markdown -> asciidoc 変換 by Pandoc on Docker
asciidoc -> html 変換 by asciidoctor Action
生成物をbuildフォルダに移動
build folderの中身をgh-pagesブランチにPush （ 参考）
そして実際のコードは以下のようになっています。


# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # asciidoc to html
  asciidoctor_job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Build AsciiDoctor
    steps:
    # Output command using asciidoctor-action
    - name: Build AsciiDoc step
      id: documents
      uses: Analog-inc/asciidoctor-action@master
      with:
        shellcommand: "asciidoctor README.adoc -r asciidoctor-diagram -a allow-uri-read -a data-uri -a toc=left" 
    # Use the output from the documents step
    - name: move deploy files
      run: |
        mkdir build/
        mv sample* build/
        ls build
    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
        publish_branch: gh-pages
